{{- if .Values.env }} 
apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ .Chart.Name }}-configmap
  labels:
    {{- include "app.labels" . | nindent 4 }}
    "helm.sh/hook": pre-install, pre-upgrade, pre-rollback
    "helm.sh/hook-weight": "-5"
data:
  {{- toYaml .Values.env | nindent 2 }}
{{- end }}
