name: Linter

on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  lint:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       chart: [ app ]

   steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Setup Helm
       uses: azure/setup-helm@v3
       with:
          version: 3.9.3

     - name: Helm lint
       run: helm lint charts/${{ matrix.chart }}
