name: Lint

on: [pull_request]

jobs:
  helm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installng Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.3

      - name: Linting chart
        run: helm lint --strict

      - name: Generate docs
        uses: gabe565/setup-helm-docs-action@v1
      - run: | 
          helm-docs
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit -m "Generate documentation"
          echo "Branch is $GITHUB_BASE_REF"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: $GITHUB_BASE_REF
          github_token: ${{ secrets.GITHUB_TOKEN }}
