name: Lint

on: [pull_request, push]

jobs:
  helm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installng Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.3

      - name: Linting chart
        run: helm lint
