name: Release chart

on:
  push:
    tags:
      - '*'

jobs:
  my-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.9.3

      - name: Check version of chart
        run: echo "Tag name is ${{ env.GITHUB_REF_NAME }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_repo_url: serhiik.github.io/universal-chart
          charts_dir: /
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: false
